obstacle_range: 10.0
raytrace_range: 10.0
#4'x8' => 1.2192m x 2.4384m 
#         0.6096m     1.2192m
#footprint: [[-0.6096, 1.2192], [0.6096, 1.2192], [0.6096, -1.2192],  [-0.6096, -1.2192]]
footprint: [[1.9384, -0.6096], [1.9384, 0.6096], [-0.5, 0.6096], [-0.5, -0.6096]]
#robot_radius: ir_of_robot
inflation_radius: .5

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: velodyne, data_type: PointCloud2, topic: ground_object_cloud, marking: false, clearing: false}
  