global_costmap:
  global_frame:     map
  robot_base_frame: base_link

  update_frequency:  5.0
  publish_frequency: 0.0

#  footprint_padding: 0.02

  # Use SLAM map
  static_map: true
  rolling_window: false
