global_costmap:
  global_frame:     /map
  robot_base_frame: base_link

  update_frequency:  5.0
  publish_frequency: 0.0

  # footprint_padding: 0.02

  # =========================== TODO: move out this reconfiguring to tt_start.launch...
  # = OPTION 1: Use static map =
  # static_map: true
  # rolling_window: false
  # = OPTION 2: Live SLAM map  =
  static_map: true
  origin_x:   0.0
  origin_y:   0.0
  width:      40.0
  height:     40.0
  origin_x:   -20.0
  origin_y:   -20.0
  # ===========================
